[build]
target = "aarch64-unknown-none"

[target.aarch64-unknown-none]
runner = [
    "qemu-system-aarch64",
    "-M", "virt",
    "-cpu", "cortex-a72",
    "-m", "512",
    "-nographic",
    "-semihosting",
    "-kernel",
]
