[build]
target = "aarch64-unknown-none"

[target.aarch64-unknown-none]
runner = [
    "qemu-system-aarch64",
    "-M", "virt",
    "-cpu", "max",
    "-m", "512",
    "-nographic",
    "-semihosting",
    "-global", "virtio-mmio.force-legacy=false",
    "-netdev", "user,id=n0",
    "-device", "virtio-net-device,netdev=n0",
    "-kernel",
]
