#![allow(dead_code)]
//! The embedded trust anchors Aurora authenticates certificate chains against.
//!
//! A trust anchor is a root CA identified by its DER-encoded Subject Name and its
//! public key. During chain verification the top presented certificate (the one
//! whose issuer is not itself in the presented set) must be signed by a root in
//! this store: its `issuer` Name must byte-for-byte equal a root's `subject`, and
//! its signature must verify under that root's public key.
//!
//! There is exactly one anchor here: the deterministic Aurora test root CA whose
//! private key is committed at `scripts/tls-testchain/root.key`. The public key
//! and Subject bytes below are those of the self-signed root that key produces,
//! so the boot-test's locally served ECDSA chain authenticates to a real root the
//! kernel embedded, not to a value smuggled in from the wire. No public web PKI
//! roots are embedded: RSA web roots would need RSA chain-signature verification,
//! and shipping roots Aurora cannot fully validate would be dishonest. Live web
//! fetches therefore report their honest (unauthenticated) level.

use crate::x509::SpkiAlg;

/// One embedded trust anchor.
pub struct TrustedRoot {
    /// DER of the root's Subject Name, the full TLV (tag+len+contents). Compared
    /// byte-for-byte against a candidate certificate's issuer Name.
    pub subject: &'static [u8],
    pub spki_alg: SpkiAlg,
    /// Public key material: EC P-256 is the SEC1 uncompressed point (0x04||X||Y).
    pub key: &'static [u8],
}

// Aurora Test Root CA (CN = "Aurora Test Root CA"), P-256. Extracted from the
// self-signed cert generated by scripts/tls-testchain/root.key.
const TEST_ROOT_SUBJECT: &[u8] = &[
    0x30, 0x1e, 0x31, 0x1c, 0x30, 0x1a, 0x06, 0x03, 0x55, 0x04, 0x03, 0x0c, 0x13, 0x41, 0x75, 0x72,
    0x6f, 0x72, 0x61, 0x20, 0x54, 0x65, 0x73, 0x74, 0x20, 0x52, 0x6f, 0x6f, 0x74, 0x20, 0x43, 0x41,
];
const TEST_ROOT_KEY: &[u8] = &[
    0x04, 0x65, 0xe9, 0x1a, 0x36, 0x38, 0x9c, 0x87, 0x70, 0x2b, 0x44, 0xa9, 0xc8, 0x6b, 0xb9, 0x29,
    0xa2, 0x0b, 0x42, 0x9a, 0xc3, 0xa0, 0x31, 0x85, 0xe1, 0xd2, 0x44, 0xa5, 0xe9, 0x65, 0xc3, 0x57,
    0x93, 0xcd, 0x95, 0x63, 0xd0, 0xe4, 0xb9, 0xff, 0x78, 0x30, 0xe8, 0xf5, 0x47, 0xb3, 0x40, 0x52,
    0xaf, 0xf8, 0x49, 0xd2, 0x85, 0x02, 0x9d, 0x81, 0xf6, 0x3f, 0xfc, 0x30, 0xdc, 0x39, 0x87, 0xbd,
    0x90,
];

static ROOTS: &[TrustedRoot] = &[TrustedRoot {
    subject: TEST_ROOT_SUBJECT,
    spki_alg: SpkiAlg::EcP256,
    key: TEST_ROOT_KEY,
}];

/// The embedded trust anchors.
pub fn roots() -> &'static [TrustedRoot] {
    ROOTS
}

/// The trust anchor whose Subject Name equals `issuer` (a DER Name TLV), if any.
pub fn find_by_subject(issuer: &[u8]) -> Option<&'static TrustedRoot> {
    ROOTS.iter().find(|r| r.subject == issuer)
}
